

version: '3.8'

services: 
  server:
    container_name: server
    image: server:0.0.4
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment: 
      - EXTERNAL_PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - PGPORT=5432
    env_file:
      - ./.env
