

version: '3.8'

services: 
  server:
    container_name: server
    image: server:0.0.4
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment: 
      - EXTERNAL_PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - PGPORT=5432
    env_file:
      - ./.env

  client:
    container_name: client
    image: client:0.0.4
    build:
      context: ./client  # Path to your client folder
      dockerfile: Dockerfile  # Optionally, specify the Dockerfile (if named differently)
    ports:
      - "3000:3000"  # Expose the port the client is running on
    depends_on:
      - server  # Ensure that the server is up before starting the client
