services:
  server:
    container_name: server
    image: server:0.0.4
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=${PORT}
      - DATABASE_URL=postgres://postgres:password@host.docker.internal:5433/transac_db
      - PGDATABASE=transac_db
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=host.docker.internal
      - PGPORT=5433
      - DATABASE_SSL=false
      - NODE_ENV=development
    env_file:
      - ./.env
    networks:
      - app-network

  client:
    container_name: client
    image: client:0.0.4
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:3001
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge